prompt_engineer_task:
  description: >
    Enhance this prompt: "{prompt}"
    For the selected AI model: {selected_model}
    Image Type: {image_type}

    Image Type-Specific Guidelines:

    Realism-Based Images:
    - Photorealistic: Focus on lighting, shadows, and real-world details
    - Hyperrealistic: Emphasize extreme detail, textures, and surface qualities
    - AI-Enhanced Realism: Balance realism with subtle AI enhancements

    Artistic & Stylized Images:
    - Illustrations: Specify art style, line work, and color palette
    - Concept Art: Include environment details, character design elements
    - Cartoon & Anime: Define style references and characteristic features
    - Pixel Art: Specify resolution and color limitations
    - Oil Painting/Watercolor/Sketch: Include medium-specific techniques

    Abstract & Surreal Images:
    - Dreamlike/Fantasy: Focus on mood, atmosphere, and impossible elements
    - Glitch/Cyberpunk: Include digital artifacts, neon elements
    - Geometric/Minimalist: Emphasize shapes, patterns, and simplicity

    Informational & Infographics:
    - Diagrams & Charts: Request clear layout and data visualization
    - Infographics: Specify text accuracy, layout structure, and data flow
    - Always include "with correct spelling and grammar"

    Specific-Use Cases:
    - Logos & Branding: Focus on scalability and brand elements
    - UI/UX Mockups: Include device context and interface elements
    - 3D Renders: Specify lighting, materials, and camera angles
    - AI-Generated Faces: Define demographic details and expressions

    Model-Specific Guidelines:

    Midjourney:
    - Use detailed descriptions and style keywords
    - Include relevant parameters (--s, --chaos, --ar, --quality)
    - Reference artistic styles or artists

    Stable Diffusion:
    - Create longer, detailed prompts
    - Include negative prompts when needed
    - Use --quality and --CFG parameters

    Leonardo AI:
    - Create a single, flowing paragraph that combines:
      * Main subject description with emotional and sensory details
      * Scene setting and environmental elements
      * Technical aspects of the image
      * Emotional undertones and mood
    - Writing style guidelines:
      * Combine all elements into one cohesive, flowing description
      * Keep descriptions tight and impactful
      * Use commas and connecting words to link ideas smoothly
      * Avoid separate paragraphs or numbered sections
      * Balance technical and emotional elements in natural language
      * Focus on the most striking visual elements
    - Key elements to weave together:
      * Subject details and actions
      * Lighting and atmosphere
      * Environmental context
      * Visual style and technical aspects
      * Emotional impact
    - Example structure:
      "[Subject details], [scene setting], [technical aspects], [emotional elements]"
      All flowing naturally as one continuous description

    DALL-E:
    - Keep prompts concise and clear
    - Only specify art medium if mentioned in original prompt
    - Focus on composition and details
    - Use descriptive adjectives for mood and atmosphere

    Adobe Firefly:
    - Use creative, imaginative concepts
    - Include text effects and color palettes
    - Optimize for Adobe tool integration

    Additional Guidelines for Infographics:
    - Explicitly request clear, legible text
    - Specify "with correct spelling and grammar"
    - For text-heavy designs, break down text elements clearly
    - Request professional typography and layout
    - Example infographic structure:
      "Create a professional infographic with clear, correctly spelled text showing [content],
       featuring legible typography, proper spacing, and accurate labels"

    Important:
    - Maintain the core elements of the original prompt
    - Don't add artistic mediums unless specified in the original prompt
    - Preserve the user's creative intent
    - Reason again and again until you are confident that you are giving correct answer
    - Think as a human being that are you giving what the user asked for? if not then try again and again till you are confident that results are what user asked for
    - For infographics, double-check that the prompt emphasizes text accuracy and clarity

  expected_output: >
    A professionally enhanced prompt optimized for {selected_model}, following
    its specific requirements and best practices while maintaining the original concept.
  agent: prompt_engineer

# image_generator_task:
#   description: >
#     Generate an image based on the prompt.
#   expected_output: >
#     A fully fledged image.
#   agent: image_generator
#   max_iterations: 1  # Limit to one attempt

